### ISSUE TITLE
Remove transports option and use URI

### ISSUE THREAD

**Issue by flowersinthesand** [vibe-project/vibe-protocol#44]
Any client transport is supposed to receive URI so that it can be used to filter available transports set from the whole. In other words, each transport should determine by URI if it is available. For example, when the whole transports are `ws`, `stream` , `longpoll` and `net` (fake), if a given URI is:
- `ws://localhost:8080/vibe`, then the available transport is `ws`.
- `http://localhost:8080/vibe`, then the available transports are `ws`, `stream` and `longpoll`.
- `tcp://localhost:8080/`, then the available transport is `net`.

Because every transport including further `http2` can deal with URI starting with `http://`, it's not large benefit. But, it makes clear that `transports` option should be configured according to URI. For example, with the above information, `ws` and `net` don't need to look up `transports` option and `http` need `transports` option consisting of `ws`, `stream` or `longpoll` to determine the final transport.

**Comment by jfarcand** [comment]
+1 on the idea.
